controller_list:
  - name: arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    allow_partial_joints_goal: True
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint

  - name: gripper_controller
    type: GripperCommand
    action_ns: gripper_action
    default: true
    joints:
      - robotiq_85_left_knuckle_joint
     
